# Generated by Django 4.2.6 on 2024-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pswrd', models.IntegerField()),
                ('user_email', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('adhaar_image', models.ImageField(default='', upload_to='activity/images')),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='slot_date',
        ),
        migrations.AlterField(
            model_name='register',
            name='parking_address',
            field=models.CharField(max_length=200),
        ),
    ]
