# Generated by Django 4.2.6 on 2024-01-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_signup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='slots',
            new_name='parking_id',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='parking_address',
            new_name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='register',
            name='slot_date',
        ),
    ]
