# Generated by Django 4.2.6 on 2024-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_register_parking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='testid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
    ]
