# Generated by Django 4.2.6 on 2024-01-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_testid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='carRegister',
        ),
    ]
