# Generated by Django 4.2.6 on 2024-01-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_register_carregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='adhaar_image',
        ),
    ]
